<?php

use Illuminate\Database\Seeder;

class KendaraanTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('kendaraan')->delete();
        
        \DB::table('kendaraan')->insert(array (
            0 => 
            array (
                'id' => 4,
                'deskripsi' => '{"deskripsi":"Colt Diesel Double Box","no":"CDD01","merk":"Mitsubishi"}',
                'ukuran' => '{"ukuran_karoseri":{"tipe":"k01","panjang":"5.6","lebar":"2","tinggi":"2.2","dalam":"24 CBM"},"ukuran_mobil":{"panjang":"6.7","lebar":"2","tinggi":"2.2"}}',
                'berat' => '{"berat_kosong":"2.5","berat_max":"8"}',
                'spesifikasi' => '{"model_mesin":"4D34-2AT7","kap_silinder":"3.908 CC","kecepatan_max":"112","tenaga_max":"136\\/2.900"}',
                'gambar' => '3.png',
                'id_jenis' => 2,
                'id_bandara' => NULL,
                'id_pelabuhan' => NULL,
                'id_stasiun' => NULL,
                'id_terminal' => NULL,
                'id_kode_pos' => NULL,
            ),
            1 => 
            array (
                'id' => 5,
                'deskripsi' => '{"deskripsi":"Colt Diesel Double Bak","no":"CDD02","merk":"Mitsubishi"}',
                'ukuran' => '{"ukuran_karoseri":{"tipe":"k02","panjang":"5.6","lebar":"2","tinggi":"2.2","dalam":"26 CBM"},"ukuran_mobil":{"panjang":"6.7","lebar":"2","tinggi":"2.2"}}',
                'berat' => '{"berat_kosong":"2.3","berat_max":"7.5"}',
                'spesifikasi' => '{"model_mesin":"4D34-2AT7","kap_silinder":"3.908 CC","kecepatan_max":"112","tenaga_max":"136\\/2.900"}',
                'gambar' => '4.jpeg',
                'id_jenis' => 2,
                'id_bandara' => NULL,
                'id_pelabuhan' => NULL,
                'id_stasiun' => NULL,
                'id_terminal' => NULL,
                'id_kode_pos' => NULL,
            ),
            2 => 
            array (
                'id' => 6,
                'deskripsi' => '{"deskripsi":"Colt Diesel Double Los Bak","no":"CDD03","merk":"Mitsubishi"}',
                'ukuran' => '{"ukuran_karoseri":{"tipe":"k03","panjang":"5.6","lebar":"2","tinggi":"tidak ada","dalam":"tidak ada"},"ukuran_mobil":{"panjang":"6.7","lebar":"2","tinggi":"2.2"}}',
                'berat' => '{"berat_kosong":"2.5","berat_max":"8"}',
                'spesifikasi' => '{"model_mesin":"4D34-2AT8","kap_silinder":"3.908 CC","kecepatan_max":"112","tenaga_max":"125\\/2.900"}',
                'gambar' => '5.jpeg',
                'id_jenis' => 2,
                'id_bandara' => NULL,
                'id_pelabuhan' => NULL,
                'id_stasiun' => NULL,
                'id_terminal' => NULL,
                'id_kode_pos' => NULL,
            ),
            3 => 
            array (
                'id' => 7,
                'deskripsi' => '{"deskripsi":"Colt Diesel Double Long Box","no":"CDD04","merk":"xxx"}',
                'ukuran' => '{"ukuran_karoseri":{"tipe":"k04","panjang":"7.2","lebar":"2.3","tinggi":"2.5","dalam":"41 CBM"},"ukuran_mobil":{"panjang":"9.4","lebar":"2.4","tinggi":"2.7"}}',
                'berat' => '{"berat_kosong":"4","berat_max":"14"}',
                'spesifikasi' => '{"model_mesin":"6D16-3AT2","kap_silinder":"7.545 CC","kecepatan_max":"96","tenaga_max":"220\\/2800"}',
                'gambar' => '6.png',
                'id_jenis' => 2,
                'id_bandara' => NULL,
                'id_pelabuhan' => NULL,
                'id_stasiun' => NULL,
                'id_terminal' => NULL,
                'id_kode_pos' => NULL,
            ),
            4 => 
            array (
                'id' => 8,
                'deskripsi' => '{"deskripsi":"Colt Diesel Double Bak Long","no":"CDD05","merk":"xxx"}',
                'ukuran' => '{"ukuran_karoseri":{"tipe":"k05","panjang":"7.2","lebar":"2.3","tinggi":"2.5","dalam":"43 CBM"},"ukuran_mobil":{"panjang":"9.4","lebar":"2.4","tinggi":"2.7"}}',
                'berat' => '{"berat_kosong":"4","berat_max":"14"}',
                'spesifikasi' => '{"model_mesin":"6D16-3AT2","kap_silinder":"7.545 CC","kecepatan_max":"96","tenaga_max":"220\\/2800"}',
                'gambar' => '7.png',
                'id_jenis' => 2,
                'id_bandara' => NULL,
                'id_pelabuhan' => NULL,
                'id_stasiun' => NULL,
                'id_terminal' => NULL,
                'id_kode_pos' => NULL,
            ),
            5 => 
            array (
                'id' => 9,
                'deskripsi' => '{"deskripsi":"Colt Diesel Double Motor Carrier Long","no":"CDD06","merk":"xxx"}',
                'ukuran' => '{"ukuran_karoseri":{"tipe":"k06","panjang":"7.2","lebar":"2.3","tinggi":"2.5","dalam":"43 CBM"},"ukuran_mobil":{"panjang":"9.4","lebar":"2.4","tinggi":"2.7"}}',
                'berat' => '{"berat_kosong":"4","berat_max":"14"}',
                'spesifikasi' => '{"model_mesin":"6D16-3AT2","kap_silinder":"7.545 CC","kecepatan_max":"96","tenaga_max":"220\\/2800"}',
                'gambar' => '8.jpeg',
                'id_jenis' => 2,
                'id_bandara' => NULL,
                'id_pelabuhan' => NULL,
                'id_stasiun' => NULL,
                'id_terminal' => NULL,
                'id_kode_pos' => NULL,
            ),
            6 => 
            array (
                'id' => 10,
                'deskripsi' => '{"deskripsi":"Colt Diesel Double Bak Air Galon","no":"CDD07","merk":"xxx"}',
                'ukuran' => '{"ukuran_karoseri":{"tipe":"k07","panjang":"7.6","lebar":"2.3","tinggi":"2.5","dalam":"43 CBM"},"ukuran_mobil":{"panjang":"8.4","lebar":"2.4","tinggi":"2.7"}}',
                'berat' => '{"berat_kosong":"4","berat_max":"14"}',
                'spesifikasi' => '{"model_mesin":"6D16-3AT2","kap_silinder":"7.545 CC","kecepatan_max":"96","tenaga_max":"220\\/2800"}',
                'gambar' => '9.jpeg',
                'id_jenis' => 2,
                'id_bandara' => NULL,
                'id_pelabuhan' => NULL,
                'id_stasiun' => NULL,
                'id_terminal' => NULL,
                'id_kode_pos' => NULL,
            ),
            7 => 
            array (
                'id' => 11,
                'deskripsi' => '{"deskripsi":"Colt Diesel Double Box Reefer","no":"CDD08","merk":"xxx"}',
                'ukuran' => '{"ukuran_karoseri":{"tipe":"k08","panjang":"5.6","lebar":"2","tinggi":"2.2","dalam":"24 CBM"},"ukuran_mobil":{"panjang":"6.7","lebar":"2","tinggi":"2.2"}}',
                'berat' => '{"berat_kosong":"2.5","berat_max":"8"}',
                'spesifikasi' => '{"model_mesin":"4D34-2AT7","kap_silinder":"3.908 CC","kecepatan_max":"112","tenaga_max":"136\\/2.900"}',
                'gambar' => '10.jpeg',
                'id_jenis' => 2,
                'id_bandara' => NULL,
                'id_pelabuhan' => NULL,
                'id_stasiun' => NULL,
                'id_terminal' => NULL,
                'id_kode_pos' => NULL,
            ),
            8 => 
            array (
                'id' => 12,
                'deskripsi' => '{"deskripsi":"Colt Diesel Engkel Box","no":"CDE01","merk":"xxx"}',
                'ukuran' => '{"ukuran_karoseri":{"tipe":"k01","panjang":"3.5","lebar":"1.6","tinggi":"1.6","dalam":"9 CBM"},"ukuran_mobil":{"panjang":"4.59","lebar":"1.69","tinggi":"2.12"}}',
                'berat' => '{"berat_kosong":"1.5","berat_max":"5.1"}',
                'spesifikasi' => '{"model_mesin":"4JB1-TC","kap_silinder":"2.771 CC","kecepatan_max":"tidak ada","tenaga_max":"100\\/3.400"}',
                'gambar' => '11.png',
                'id_jenis' => 2,
                'id_bandara' => NULL,
                'id_pelabuhan' => NULL,
                'id_stasiun' => NULL,
                'id_terminal' => NULL,
                'id_kode_pos' => NULL,
            ),
            9 => 
            array (
                'id' => 13,
                'deskripsi' => '{"deskripsi":"Colt Diesel Engkel Bak","no":"CDE02","merk":"xxx"}',
                'ukuran' => '{"ukuran_karoseri":{"tipe":"k02","panjang":"3.5","lebar":"1.6","tinggi":"0.8","dalam":"10 CBM"},"ukuran_mobil":{"panjang":"4.59","lebar":"1.69","tinggi":"2.12"}}',
                'berat' => '{"berat_kosong":"1.5","berat_max":"5.1"}',
                'spesifikasi' => '{"model_mesin":"4JB1-TC","kap_silinder":"2.771 CC","kecepatan_max":"tidak ada","tenaga_max":"100\\/3.400"}',
                'gambar' => '12.jpeg',
                'id_jenis' => 2,
                'id_bandara' => NULL,
                'id_pelabuhan' => NULL,
                'id_stasiun' => NULL,
                'id_terminal' => NULL,
                'id_kode_pos' => NULL,
            ),
            10 => 
            array (
                'id' => 14,
                'deskripsi' => '{"deskripsi":"Colt Diesel Engkel Los Bak","no":"CDE03","merk":"xxx"}',
                'ukuran' => '{"ukuran_karoseri":{"tipe":"k03","panjang":"3.5","lebar":"1.73","tinggi":"tidak ada","dalam":"11 CBM"},"ukuran_mobil":{"panjang":"4.73","lebar":"1.75","tinggi":"2.05"}}',
                'berat' => '{"berat_kosong":"1.8","berat_max":"5"}',
                'spesifikasi' => '{"model_mesin":"4D34-2AT5","kap_silinder":"3.908 CC","kecepatan_max":"116","tenaga_max":"110\\/2.900"}',
                'gambar' => '13.png',
                'id_jenis' => 2,
                'id_bandara' => NULL,
                'id_pelabuhan' => NULL,
                'id_stasiun' => NULL,
                'id_terminal' => NULL,
                'id_kode_pos' => NULL,
            ),
            11 => 
            array (
                'id' => 15,
                'deskripsi' => '{"deskripsi":"Pick Up L300 Bak","no":"PU01","merk":"xxx"}',
                'ukuran' => '{"ukuran_karoseri":{"tipe":"k01","panjang":"2.42","lebar":"1.44","tinggi":"0.3","dalam":"6 CBM"},"ukuran_mobil":{"panjang":"3.72","lebar":"1.83","tinggi":"1.82"}}',
                'berat' => '{"berat_kosong":"0.8","berat_max":"2"}',
                'spesifikasi' => '{"model_mesin":"G15A","kap_silinder":"1.493 CC","kecepatan_max":"tidak ada","tenaga_max":"78.8\\/5.500"}',
                'gambar' => '14.jpeg',
                'id_jenis' => 2,
                'id_bandara' => NULL,
                'id_pelabuhan' => NULL,
                'id_stasiun' => NULL,
                'id_terminal' => NULL,
                'id_kode_pos' => NULL,
            ),
            12 => 
            array (
                'id' => 18,
                'deskripsi' => '{"deskripsi":"Contoh kapal","no":"10","merk":"asbd"}',
                'ukuran' => '{"ukuran_karoseri":{"tipe":"DEF","panjang":"100","lebar":"200","tinggi":"102","dalam":"100"},"ukuran_mobil":{"panjang":"13","lebar":"100","tinggi":"15"}}',
                'berat' => '{"berat_kosong":"100","berat_max":"20"}',
                'spesifikasi' => '{"model_mesin":"Honda","kap_silinder":"100","kecepatan_max":"100","tenaga_max":"360"}',
                'gambar' => '17.jpeg',
                'id_jenis' => 3,
                'id_bandara' => NULL,
                'id_pelabuhan' => NULL,
                'id_stasiun' => NULL,
                'id_terminal' => NULL,
                'id_kode_pos' => NULL,
            ),
            13 => 
            array (
                'id' => 19,
                'deskripsi' => '{"deskripsi":"Contoh Kereta Api","no":"ABC","merk":"DEF"}',
                'ukuran' => '{"ukuran_karoseri":{"tipe":"XYZ","panjang":"100","lebar":"101","tinggi":"102","dalam":"103"},"ukuran_mobil":{"panjang":"200","lebar":"300","tinggi":"400"}}',
                'berat' => '{"berat_kosong":"50","berat_max":"100"}',
                'spesifikasi' => '{"model_mesin":"AB3","kap_silinder":"100","kecepatan_max":"120","tenaga_max":"150"}',
                'gambar' => '18.jpeg',
                'id_jenis' => 5,
                'id_bandara' => NULL,
                'id_pelabuhan' => NULL,
                'id_stasiun' => NULL,
                'id_terminal' => NULL,
                'id_kode_pos' => NULL,
            ),
            14 => 
            array (
                'id' => 20,
                'deskripsi' => '{"deskripsi":"Contoh Pesawat","no":"L123","merk":"Lion Air"}',
                'ukuran' => '{"ukuran_karoseri":{"tipe":"GGG","panjang":"100","lebar":"102","tinggi":"103","dalam":"104"},"ukuran_mobil":{"panjang":"105","lebar":"106","tinggi":"107"}}',
                'berat' => '{"berat_kosong":"10","berat_max":"110"}',
                'spesifikasi' => '{"model_mesin":"JKL","kap_silinder":"100","kecepatan_max":"200","tenaga_max":"500"}',
                'gambar' => '19.jpeg',
                'id_jenis' => 4,
                'id_bandara' => NULL,
                'id_pelabuhan' => NULL,
                'id_stasiun' => NULL,
                'id_terminal' => NULL,
                'id_kode_pos' => NULL,
            ),
            15 => 
            array (
                'id' => 22,
                'deskripsi' => '{"deskripsi":"Tronton Box","no":"TR01","merk":"xxx"}',
                'ukuran' => '{"ukuran_karoseri":{"tipe":"k01","panjang":"6.3","lebar":"2.2","tinggi":"2.3","dalam":"30 CBM"},"ukuran_mobil":{"panjang":"11.9","lebar":"2.5","tinggi":"2.9"}}',
                'berat' => '{"berat_kosong":"7.2","berat_max":"15"}',
                'spesifikasi' => '{"model_mesin":"6S20","kap_silinder":"tidak ada","kecepatan_max":"90","tenaga_max":"230\\/2.200"}',
                'gambar' => '21.png',
                'id_jenis' => 2,
                'id_bandara' => NULL,
                'id_pelabuhan' => NULL,
                'id_stasiun' => NULL,
                'id_terminal' => NULL,
                'id_kode_pos' => NULL,
            ),
            16 => 
            array (
                'id' => 23,
                'deskripsi' => '{"deskripsi":"Tronton Bak","no":"TR02","merk":"xxx"}',
                'ukuran' => '{"ukuran_karoseri":{"tipe":"k02","panjang":"6.3","lebar":"2.2","tinggi":"2.3","dalam":"30 CBM"},"ukuran_mobil":{"panjang":"11.9","lebar":"2.5","tinggi":"2.9"}}',
                'berat' => '{"berat_kosong":"7.2","berat_max":"15"}',
                'spesifikasi' => '{"model_mesin":"6S20","kap_silinder":"tidak ada","kecepatan_max":"90","tenaga_max":"230\\/2.200"}',
                'gambar' => '22.png',
                'id_jenis' => 2,
                'id_bandara' => NULL,
                'id_pelabuhan' => NULL,
                'id_stasiun' => NULL,
                'id_terminal' => NULL,
                'id_kode_pos' => NULL,
            ),
            17 => 
            array (
                'id' => 24,
                'deskripsi' => '{"deskripsi":"Tronton Flat Deck","no":"TR03","merk":"xxx"}',
                'ukuran' => '{"ukuran_karoseri":{"tipe":"k03","panjang":"6.3","lebar":"2.2","tinggi":"tidak ada","dalam":"30 CBM"},"ukuran_mobil":{"panjang":"11.9","lebar":"2.5","tinggi":"2.9"}}',
                'berat' => '{"berat_kosong":"7.2","berat_max":"15"}',
                'spesifikasi' => '{"model_mesin":"6S20","kap_silinder":"tidak ada","kecepatan_max":"90","tenaga_max":"230\\/2.200"}',
                'gambar' => '23.png',
                'id_jenis' => 2,
                'id_bandara' => NULL,
                'id_pelabuhan' => NULL,
                'id_stasiun' => NULL,
                'id_terminal' => NULL,
                'id_kode_pos' => NULL,
            ),
            18 => 
            array (
                'id' => 25,
                'deskripsi' => '{"deskripsi":"Tronton Car Carrier","no":"TR04","merk":"xxx"}',
                'ukuran' => '{"ukuran_karoseri":{"tipe":"k04","panjang":"6.3","lebar":"2.2","tinggi":"2.3","dalam":"30 CBM"},"ukuran_mobil":{"panjang":"11.9","lebar":"2.5","tinggi":"2.9"}}',
                'berat' => '{"berat_kosong":"7.2","berat_max":"15"}',
                'spesifikasi' => '{"model_mesin":"6S20","kap_silinder":"tidak ada","kecepatan_max":"90","tenaga_max":"230\\/2.200"}',
                'gambar' => '24.png',
                'id_jenis' => 2,
                'id_bandara' => NULL,
                'id_pelabuhan' => NULL,
                'id_stasiun' => NULL,
                'id_terminal' => NULL,
                'id_kode_pos' => NULL,
            ),
            19 => 
            array (
                'id' => 26,
                'deskripsi' => '{"deskripsi":"Tronton Reefer","no":"TR05","merk":"xxx"}',
                'ukuran' => '{"ukuran_karoseri":{"tipe":"k05","panjang":"6.3","lebar":"2.2","tinggi":"2.3","dalam":"30 CBM"},"ukuran_mobil":{"panjang":"11.9","lebar":"2.5","tinggi":"2.9"}}',
                'berat' => '{"berat_kosong":"7.2","berat_max":"10"}',
                'spesifikasi' => '{"model_mesin":"6S20","kap_silinder":"tidak ada","kecepatan_max":"90","tenaga_max":"230\\/2.200"}',
                'gambar' => '25.png',
                'id_jenis' => 2,
                'id_bandara' => NULL,
                'id_pelabuhan' => NULL,
                'id_stasiun' => NULL,
                'id_terminal' => NULL,
                'id_kode_pos' => NULL,
            ),
            20 => 
            array (
                'id' => 27,
                'deskripsi' => '{"deskripsi":"Pick Up Box","no":"PU02","merk":"xxx"}',
                'ukuran' => '{"ukuran_karoseri":{"tipe":"k02","panjang":"2.37","lebar":"1.55","tinggi":"1.29","dalam":"4 CBM"},"ukuran_mobil":{"panjang":"4.28","lebar":"1.67","tinggi":"2.07"}}',
                'berat' => '{"berat_kosong":"1","berat_max":"1.5"}',
                'spesifikasi' => '{"model_mesin":"3SZ - VE, DOHC VVTi berpendingin air","kap_silinder":"1.298 CC","kecepatan_max":"tidak ada","tenaga_max":"88\\/6.000"}',
                'gambar' => '24.jpeg',
                'id_jenis' => 2,
                'id_bandara' => NULL,
                'id_pelabuhan' => NULL,
                'id_stasiun' => NULL,
                'id_terminal' => NULL,
                'id_kode_pos' => NULL,
            ),
            21 => 
            array (
                'id' => 28,
                'deskripsi' => '{"deskripsi":"Pick Up Reefer","no":"PU03","merk":"xxx"}',
                'ukuran' => '{"ukuran_karoseri":{"tipe":"k03","panjang":"2.37","lebar":"1.55","tinggi":"1.29","dalam":"4 CBM"},"ukuran_mobil":{"panjang":"4.28","lebar":"1.67","tinggi":"2.07"}}',
                'berat' => '{"berat_kosong":"1","berat_max":"1.5"}',
                'spesifikasi' => '{"model_mesin":"3SZ - VE, DOHC VVTi berpendingin air","kap_silinder":"1.298 CC","kecepatan_max":"tidak ada","tenaga_max":"88\\/6.000"}',
                'gambar' => '25.jpeg',
                'id_jenis' => 2,
                'id_bandara' => NULL,
                'id_pelabuhan' => NULL,
                'id_stasiun' => NULL,
                'id_terminal' => NULL,
                'id_kode_pos' => NULL,
            ),
        ));
        
        
    }
}